# Generated by Django 5.2.9 on 2026-01-01 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video'), ('ARTICLE', 'Article')], default='VIDEO', max_length=20)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('CORE', 'Core'), ('NICE_TO_HAVE', 'Nice to Have')], default='CORE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('COMPLETED', 'Completed')], default='STARTED', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='learning.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='NOT_STARTED', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning.learningcontent')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='learning.employee')),
            ],
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_contents', to='learning.skill'),
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='learning.assessmentsession')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.skill')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='learning.skill')),
            ],
        ),
    ]
