# Generated by Django 5.2.9 on 2026-01-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_learningcontent_skill_assessmentsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='correct_option',
            field=models.CharField(default='A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='options',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
