# Generated by Django 5.2.9 on 2026-01-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_assessmentquestion_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcontent',
            name='content_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
