# Generated by Django 5.2.9 on 2026-01-09 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_learningcontent_content_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPathItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=100)),
                ('url', models.TextField()),
                ('thumbnail', models.TextField()),
                ('estimated_hours', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='NOT_STARTED', max_length=20)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningpath')),
            ],
        ),
    ]
