# Generated by Django 5.2.9 on 2026-01-14 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_learningpathitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.assessmentsession'),
        ),
    ]
