# Generated by Django 5.2.9 on 2026-01-14 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_assessmentquestion_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.assessmentsession'),
        ),
    ]
